### ISSUE TITLE
Balancemastering Teufelsberg NSA tower IR link seems to redirect to some shady site

### ISSUE THREAD

**Issue by patrickhlauke** [IsaakCode/freeaudio#2]
Just stumbled across this as I was looking for a link to those impulse response files, and following the link takes you to some intermediate site that wants you to run an installer - supposedly for a "safe browsing" extension. Suggest removing it...

**Comment by IsaakCode** [comment]
Thanks for the heads-up! I replaced the link, the original website is no longer functional apparently.
